// Generated by SolidPython 0.4.6 on 2020-01-16 21:43:11


difference() {
	cube(size = 10);
	sphere(r = 15);
}
/***********************************************
*********      SolidPython code:      **********
************************************************
 
# This is a testing file for Solid Python
# Use this file to learn the ropes of Solid Python

from solid import *
from solid.utils import *  # Not required, but the utils module is useful

d = difference()(
    cube(10),  # Note the comma between each element!
    sphere(15)
)

scad_render_to_file(d, 'Test.scad')
 
 
************************************************/
